name: Deploy to Amazon S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up environment variables
      run: |
        echo "REACT_APP_BACKEND_URL=https://main-backend.reservele.com/" >> $GITHUB_ENV  # change this to your main backend URL

    - name: Check environment variable after setup
      run: |
        echo "REACT_APP_BACKEND_URL is ${{ env.REACT_APP_BACKEND_URL }}"

    - name: Install dependencies and build
      run: |
        npm ci
        echo "=== BEFORE BUILD ==="
        echo "REACT_APP_BACKEND_URL is ${{ env.REACT_APP_BACKEND_URL }}"
        echo "=== END BEFORE BUILD ==="
        export NODE_ENV=production
        npm run build

    - name: Check environment variable after build
      run: |
        echo "REACT_APP_BACKEND_URL is ${{ env.REACT_APP_BACKEND_URL }}"

    - name: Deploy to S3
      run: |
        aws s3 sync build/ s3://${{ secrets.heartbeat.cuoremo.co.jp }}/ --delete
