name: Deploy to Amazon S3

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up environment variables
      run: |
        echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL_STAGING }}" >> $GITHUB_ENV

    - name: Check environment variable after setup
      run: |
        echo "REACT_APP_BACKEND_URL is ${{ env.REACT_APP_BACKEND_URL_STAGING }}"

    - name: Install dependencies and build
      run: |
        npm ci
        echo "=== BEFORE BUILD ==="
        echo "REACT_APP_BACKEND_URL is ${{ env.REACT_APP_BACKEND_URL_STAGING }}"
        echo "=== END BEFORE BUILD ==="
        export NODE_ENV=production
        npm run build

    - name: Check environment variable after build
      run: |
        echo "REACT_APP_BACKEND_URL is ${{ env.REACT_APP_BACKEND_URL_STAGING }}"

    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME_STAGING }}/ --delete
