name: Deploy to Amazon S3 (main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install dependencies
      run: npm ci

    - name: Configure constants.js for main
      run: cp src/utils/constants-main.js src/utils/constants.js  # src/utils/はconstants.jsが置いてあるディレクトリに合わせてください

    - name: Build the project
      run: |
        echo "=== BEFORE BUILD ==="
        export NODE_ENV=production
        npm run build:debug
        echo "=== END BEFORE BUILD ==="

    - name: Deploy to S3
      run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME_PRODUCTION }}/ --delete #production (www.heart-beat.me)