# Staging YAML2#

name: Deploy to Amazon S3

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up environment variables
      run: |
        echo "REACT_APP_BACKEND_URL=https://staging-backend.reservele.com/" > .env.production.local

    - name: Check environment variable in .env.production.local after setup
      run: |
        cat .env.production.local

    - name: Install dependencies and build
      run: |
        npm ci
        echo "=== BEFORE BUILD ==="
        cat .env.production.local
        echo "=== END BEFORE BUILD ==="
        export NODE_ENV=production
        npm run build

    - name: Check environment variable in .env.production.local after build
      run: |
        cat .env.production.local

    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME_STAGING }}/ --delete
